# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 0) do

  create_table "gwsub_sb01_training_files", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.integer  "parent_id"
    t.integer  "title_id"
    t.string   "content_type"
    t.text     "filename"
    t.text     "memo"
    t.integer  "size"
    t.integer  "width"
    t.integer  "height"
    t.integer  "db_file_id"
  end

  create_table "gwsub_sb01_training_guides", :force => true do |t|
    t.text     "categories"
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.text     "title"
    t.text     "bbs_url"
    t.text     "remarks"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.text     "state"
    t.integer  "member_id"
    t.integer  "group_id"
  end

  create_table "gwsub_sb01_training_schedule_conditions", :force => true do |t|
    t.integer  "training_id"
    t.integer  "members_max"
    t.text     "title"
    t.text     "from_start"
    t.text     "from_start_min"
    t.text     "from_end"
    t.text     "from_end_min"
    t.integer  "member_id"
    t.integer  "prop_id"
    t.text     "repeat_flg"
    t.text     "repeat_monthly"
    t.text     "repeat_weekday"
    t.datetime "from_at"
    t.datetime "to_at"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.text     "state"
    t.integer  "group_id"
    t.text     "extension"
    t.integer  "prop_kind"
    t.text     "prop_name"
    t.integer  "repeat_class_id"
  end

  create_table "gwsub_sb01_training_schedule_members", :force => true do |t|
    t.integer  "training_id"
    t.integer  "schedule_id"
    t.integer  "condition_id"
    t.integer  "training_schedule_id"
    t.integer  "training_user_id"
    t.integer  "training_group_id"
    t.integer  "entry_user_id"
    t.integer  "entry_group_id"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.text     "training_user_tel"
    t.text     "entry_user_tel"
  end

  create_table "gwsub_sb01_training_schedule_props", :force => true do |t|
    t.integer  "training_id"
    t.integer  "schedule_id"
    t.integer  "prop_id"
    t.integer  "members_max"
    t.integer  "members_current"
    t.integer  "member_id"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.integer  "condition_id"
    t.text     "from_start"
    t.text     "from_end"
    t.text     "state"
    t.integer  "group_id"
  end

  create_table "gwsub_sb01_training_schedules", :force => true do |t|
    t.integer  "schedule_id"
    t.integer  "training_id"
    t.integer  "condition_id"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.integer  "members_max"
    t.integer  "members_current"
    t.text     "state"
    t.datetime "from_start"
    t.datetime "from_end"
    t.text     "prop_name"
  end

  create_table "gwsub_sb01_trainings", :force => true do |t|
    t.text     "categories"
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.text     "title"
    t.text     "bbs_url"
    t.text     "body"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.text     "state"
    t.integer  "member_id"
    t.integer  "group_id"
    t.integer  "member_max"
    t.text     "group_code"
    t.text     "group_name"
    t.text     "member_code"
    t.text     "member_name"
    t.text     "member_tel"
    t.integer  "bbs_doc_id"
  end

  create_table "gwsub_sb04_check_assignedjobs", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.integer  "section_id"
    t.text     "section_code"
    t.text     "section_name"
    t.integer  "code_int"
    t.text     "code"
    t.text     "name"
    t.text     "tel"
    t.text     "address"
    t.text     "remarks"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwsub_sb04_check_officialtitles", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.integer  "code_int"
    t.text     "code"
    t.text     "name"
    t.text     "remarks"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwsub_sb04_check_sections", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.text     "code"
    t.text     "name"
    t.text     "remarks"
    t.text     "bbs_url"
    t.text     "ldap_code"
    t.text     "ldap_name"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwsub_sb04_check_stafflists", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.text     "staff_no"
    t.text     "multi_section_flg"
    t.text     "name"
    t.text     "name_print"
    t.text     "kana"
    t.integer  "section_id"
    t.text     "section_code"
    t.text     "section_name"
    t.integer  "assignedjobs_id"
    t.integer  "assignedjobs_code_int"
    t.text     "assignedjobs_code"
    t.text     "assignedjobs_name"
    t.text     "assignedjobs_tel"
    t.text     "assignedjobs_address"
    t.integer  "official_title_id"
    t.text     "official_title_code"
    t.integer  "official_title_code_int"
    t.text     "official_title_name"
    t.integer  "categories_id"
    t.text     "categories_code"
    t.text     "categories_name"
    t.text     "extension"
    t.text     "divide_duties"
    t.text     "divide_duties_order"
    t.integer  "divide_duties_order_int"
    t.text     "remarks"
    t.text     "personal_state"
    t.text     "display_state"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwsub_sb04_editable_dates", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.datetime "published_at"
    t.datetime "start_at"
    t.datetime "end_at"
    t.datetime "headline_at"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
  end

  create_table "gwsub_sb04_limit_settings", :force => true do |t|
    t.string   "type_name"
    t.integer  "limit"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
  end

  create_table "gwsub_sb04_seating_lists", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.text     "title"
    t.text     "bbs_url"
    t.text     "remarks"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
  end

  create_table "gwsub_sb04_year_copy_logs", :force => true do |t|
    t.string   "type"
    t.integer  "origin_fyear_id"
    t.integer  "origin_section_id"
    t.string   "origin_section_code"
    t.text     "origin_section_name"
    t.integer  "destination_fyear_id"
    t.integer  "destination_section_id"
    t.string   "destination_section_code"
    t.text     "destination_section_name"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwsub_sb04assignedjobs", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.integer  "section_id"
    t.text     "section_code"
    t.text     "section_name"
    t.integer  "code_int"
    t.text     "code"
    t.text     "name"
    t.text     "tel"
    t.text     "address"
    t.text     "remarks"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwsub_sb04helps", :force => true do |t|
    t.integer  "categories"
    t.text     "title"
    t.text     "bbs_url"
    t.text     "remarks"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwsub_sb04officialtitles", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.integer  "code_int"
    t.text     "code"
    t.text     "name"
    t.text     "remarks"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwsub_sb04sections", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.text     "code"
    t.text     "name"
    t.text     "remarks"
    t.text     "bbs_url"
    t.text     "ldap_code"
    t.text     "ldap_name"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  add_index "gwsub_sb04sections", ["code"], :name => "code", :length => {"code"=>10}
  add_index "gwsub_sb04sections", ["fyear_id"], :name => "fyear_id"

  create_table "gwsub_sb04stafflists", :force => true do |t|
    t.integer  "fyear_id"
    t.text     "fyear_markjp"
    t.text     "staff_no"
    t.text     "multi_section_flg"
    t.text     "name"
    t.text     "name_print"
    t.text     "kana"
    t.integer  "section_id"
    t.text     "section_code"
    t.text     "section_name"
    t.integer  "assignedjobs_id"
    t.integer  "assignedjobs_code_int"
    t.text     "assignedjobs_code"
    t.text     "assignedjobs_name"
    t.text     "assignedjobs_tel"
    t.text     "assignedjobs_address"
    t.integer  "official_title_id"
    t.text     "official_title_code"
    t.integer  "official_title_code_int"
    t.text     "official_title_name"
    t.integer  "categories_id"
    t.text     "categories_code"
    t.text     "categories_name"
    t.text     "extension"
    t.text     "divide_duties"
    t.text     "divide_duties_order"
    t.integer  "divide_duties_order_int"
    t.text     "remarks"
    t.text     "personal_state"
    t.text     "display_state"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  add_index "gwsub_sb04stafflists", ["fyear_id"], :name => "fyear_id"
  add_index "gwsub_sb04stafflists", ["fyear_markjp"], :name => "fyear_markjp", :length => {"fyear_markjp"=>10}

end
