# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20140718085409) do

  create_table "digitallibrary_adms", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "digitallibrary_controls", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.integer  "default_published"
    t.integer  "upload_graphic_file_size_capacity"
    t.string   "upload_graphic_file_size_capacity_unit"
    t.integer  "upload_document_file_size_capacity"
    t.string   "upload_document_file_size_capacity_unit"
    t.integer  "upload_graphic_file_size_max"
    t.integer  "upload_document_file_size_max"
    t.decimal  "upload_graphic_file_size_currently",                    :precision => 17, :scale => 0
    t.decimal  "upload_document_file_size_currently",                   :precision => 17, :scale => 0
    t.string   "create_section"
    t.integer  "addnew_forbidden"
    t.integer  "draft_forbidden"
    t.integer  "delete_forbidden"
    t.integer  "importance"
    t.string   "form_name"
    t.text     "banner"
    t.string   "banner_position"
    t.text     "left_banner"
    t.text     "left_menu"
    t.string   "left_index_use",                          :limit => 1
    t.string   "left_index_bg_color"
    t.string   "default_folder"
    t.text     "other_system_link"
    t.text     "wallpaper"
    t.text     "css"
    t.integer  "sort_no"
    t.text     "caption"
    t.boolean  "view_hide"
    t.boolean  "categoey_view"
    t.integer  "categoey_view_line"
    t.boolean  "monthly_view"
    t.integer  "monthly_view_line"
    t.integer  "notification"
    t.integer  "upload_system"
    t.string   "limit_date"
    t.string   "separator_str1"
    t.string   "separator_str2"
    t.string   "name"
    t.string   "title"
    t.integer  "category"
    t.string   "category1_name"
    t.string   "category2_name"
    t.string   "category3_name"
    t.integer  "recognize"
    t.text     "createdate"
    t.string   "createrdivision_id",                      :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                              :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",                       :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                               :limit => 20
    t.text     "editor"
    t.integer  "default_limit"
    t.string   "dbname"
    t.text     "admingrps"
    t.text     "admingrps_json"
    t.text     "adms"
    t.text     "adms_json"
    t.text     "dsp_admin_name"
    t.text     "editors"
    t.text     "editors_json"
    t.text     "readers"
    t.text     "readers_json"
    t.text     "sueditors"
    t.text     "sueditors_json"
    t.text     "sureaders"
    t.text     "sureaders_json"
    t.text     "help_display"
    t.text     "help_url"
    t.text     "help_admin_url"
    t.datetime "docslast_updated_at"
  end

  create_table "digitallibrary_roles", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.string   "role_code"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "doclibrary_adms", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "doclibrary_controls", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.integer  "default_published"
    t.integer  "upload_graphic_file_size_capacity"
    t.string   "upload_graphic_file_size_capacity_unit"
    t.integer  "upload_document_file_size_capacity"
    t.string   "upload_document_file_size_capacity_unit"
    t.integer  "upload_graphic_file_size_max"
    t.integer  "upload_document_file_size_max"
    t.decimal  "upload_graphic_file_size_currently",                    :precision => 17, :scale => 0
    t.decimal  "upload_document_file_size_currently",                   :precision => 17, :scale => 0
    t.string   "create_section"
    t.integer  "addnew_forbidden"
    t.integer  "draft_forbidden"
    t.integer  "delete_forbidden"
    t.integer  "importance"
    t.string   "form_name"
    t.text     "banner"
    t.string   "banner_position"
    t.text     "left_banner"
    t.text     "left_menu"
    t.string   "left_index_use",                          :limit => 1
    t.string   "left_index_bg_color"
    t.string   "default_folder"
    t.text     "other_system_link"
    t.text     "wallpaper"
    t.text     "css"
    t.integer  "sort_no"
    t.text     "caption"
    t.boolean  "view_hide"
    t.boolean  "categoey_view"
    t.integer  "categoey_view_line"
    t.boolean  "monthly_view"
    t.integer  "monthly_view_line"
    t.integer  "notification"
    t.integer  "upload_system"
    t.string   "limit_date"
    t.string   "name"
    t.string   "title"
    t.integer  "category"
    t.string   "category1_name"
    t.string   "category2_name"
    t.string   "category3_name"
    t.integer  "recognize"
    t.text     "createdate"
    t.string   "createrdivision_id",                      :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                              :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",                       :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                               :limit => 20
    t.text     "editor"
    t.integer  "default_limit"
    t.string   "dbname"
    t.text     "admingrps"
    t.text     "admingrps_json"
    t.text     "adms"
    t.text     "adms_json"
    t.text     "dsp_admin_name"
    t.text     "editors"
    t.text     "editors_json"
    t.text     "readers"
    t.text     "readers_json"
    t.text     "sueditors"
    t.text     "sueditors_json"
    t.text     "sureaders"
    t.text     "sureaders_json"
    t.text     "help_display"
    t.text     "help_url"
    t.text     "help_admin_url"
    t.text     "special_link"
    t.datetime "docslast_updated_at"
  end

  create_table "doclibrary_roles", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.string   "role_code"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "enquete_answers", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "latest_updated_at"
    t.boolean  "enquete_division"
    t.integer  "title_id"
    t.string   "user_code"
    t.text     "user_name"
    t.string   "l2_section_code"
    t.string   "section_code"
    t.text     "section_name"
    t.integer  "section_sort"
    t.text     "field_001"
    t.text     "field_002"
    t.text     "field_003"
    t.text     "field_004"
    t.text     "field_005"
    t.text     "field_006"
    t.text     "field_007"
    t.text     "field_008"
    t.text     "field_009"
    t.text     "field_010"
    t.text     "field_011"
    t.text     "field_012"
    t.text     "field_013"
    t.text     "field_014"
    t.text     "field_015"
    t.text     "field_016"
    t.text     "field_017"
    t.text     "field_018"
    t.text     "field_019"
    t.text     "field_020"
    t.text     "field_021"
    t.text     "field_022"
    t.text     "field_023"
    t.text     "field_024"
    t.text     "field_025"
    t.text     "field_026"
    t.text     "field_027"
    t.text     "field_028"
    t.text     "field_029"
    t.text     "field_030"
    t.text     "field_031"
    t.text     "field_032"
    t.text     "field_033"
    t.text     "field_034"
    t.text     "field_035"
    t.text     "field_036"
    t.text     "field_037"
    t.text     "field_038"
    t.text     "field_039"
    t.text     "field_040"
    t.text     "field_041"
    t.text     "field_042"
    t.text     "field_043"
    t.text     "field_044"
    t.text     "field_045"
    t.text     "field_046"
    t.text     "field_047"
    t.text     "field_048"
    t.text     "field_049"
    t.text     "field_050"
    t.text     "field_051"
    t.text     "field_052"
    t.text     "field_053"
    t.text     "field_054"
    t.text     "field_055"
    t.text     "field_056"
    t.text     "field_057"
    t.text     "field_058"
    t.text     "field_059"
    t.text     "field_060"
    t.text     "field_061"
    t.text     "field_062"
    t.text     "field_063"
    t.text     "field_064"
    t.text     "createdate"
    t.string   "createrdivision_id", :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",         :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",  :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",          :limit => 20
    t.text     "editor"
    t.datetime "able_date"
    t.datetime "expiry_date"
  end

  add_index "enquete_answers", ["user_code"], :name => "user_code"

  create_table "enquete_base_users", :force => true do |t|
    t.integer  "unid"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "base_user_code"
    t.text     "base_user_name"
  end

  add_index "enquete_base_users", ["base_user_code"], :name => "base_user_code"

  create_table "enquete_view_questions", :id => false, :force => true do |t|
    t.string   "base_user_code"
    t.integer  "id",                                :default => 0, :null => false
    t.integer  "unid"
    t.boolean  "include_index"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "section_code"
    t.string   "section_name"
    t.integer  "section_sort"
    t.boolean  "enquete_division"
    t.string   "manage_title"
    t.string   "title"
    t.text     "form_body"
    t.datetime "able_date"
    t.datetime "expiry_date"
    t.integer  "spec_config"
    t.string   "send_change"
    t.text     "createdate"
    t.string   "createrdivision_id",  :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",          :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",   :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",           :limit => 20
    t.text     "editor"
    t.text     "custom_groups"
    t.text     "custom_groups_json"
    t.text     "reader_groups"
    t.text     "reader_groups_json"
    t.text     "custom_readers"
    t.text     "custom_readers_json"
    t.text     "readers"
    t.text     "readers_json"
    t.integer  "default_limit"
  end

  create_table "gw_admin_check_extensions", :force => true do |t|
    t.string   "state"
    t.integer  "sort_no"
    t.string   "extension"
    t.text     "remark"
    t.datetime "deleted_at"
    t.integer  "deleted_uid"
    t.integer  "deleted_gid"
    t.datetime "updated_at"
    t.integer  "updated_uid"
    t.integer  "updated_gid"
    t.datetime "created_at"
    t.integer  "created_uid"
    t.integer  "created_gid"
  end

  create_table "gw_admin_messages", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "body"
    t.integer  "sort_no"
    t.integer  "state"
  end

  create_table "gw_blog_parts", :force => true do |t|
    t.text     "state"
    t.integer  "sort_no"
    t.text     "title"
    t.text     "body"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "deleted_at"
    t.text     "deleted_user"
    t.text     "deleted_group"
  end

  create_table "gw_circulars", :force => true do |t|
    t.integer  "state"
    t.integer  "uid"
    t.string   "u_code"
    t.integer  "gid"
    t.string   "g_code"
    t.integer  "class_id"
    t.text     "title"
    t.datetime "st_at"
    t.datetime "ed_at"
    t.integer  "is_finished"
    t.integer  "is_system"
    t.text     "options"
    t.text     "body"
    t.datetime "deleted_at"
    t.datetime "updated_at"
    t.datetime "created_at"
  end

  add_index "gw_circulars", ["ed_at"], :name => "ed_at"
  add_index "gw_circulars", ["state"], :name => "state"
  add_index "gw_circulars", ["uid"], :name => "uid"

  create_table "gw_edit_link_piece_csses", :force => true do |t|
    t.string   "state"
    t.string   "css_name"
    t.integer  "css_sort_no",   :default => 0
    t.string   "css_class"
    t.integer  "css_type",      :default => 1
    t.datetime "deleted_at"
    t.string   "deleted_user"
    t.string   "deleted_group"
    t.datetime "updated_at"
    t.string   "updated_user"
    t.string   "updated_group"
    t.datetime "created_at"
    t.string   "created_user"
    t.string   "created_group"
  end

  create_table "gw_edit_link_pieces", :force => true do |t|
    t.integer  "uid"
    t.integer  "class_created",     :default => 0
    t.string   "published"
    t.string   "state"
    t.integer  "level_no",          :default => 0
    t.integer  "parent_id",         :default => 0
    t.string   "name"
    t.integer  "sort_no",           :default => 0
    t.integer  "tab_keys",          :default => 0
    t.integer  "display_auth_priv"
    t.integer  "role_name_id"
    t.text     "display_auth"
    t.integer  "block_icon_id"
    t.integer  "block_css_id"
    t.text     "link_url"
    t.text     "remark"
    t.text     "icon_path"
    t.string   "link_div_class"
    t.integer  "class_external",    :default => 0
    t.integer  "ssoid"
    t.integer  "class_sso",         :default => 0
    t.string   "field_account"
    t.string   "field_pass"
    t.integer  "css_id",            :default => 0
    t.datetime "deleted_at"
    t.string   "deleted_user"
    t.string   "deleted_group"
    t.datetime "updated_at"
    t.string   "updated_user"
    t.string   "updated_group"
    t.datetime "created_at"
    t.string   "created_user"
    t.string   "created_group"
    t.integer  "location"
  end

  create_table "gw_edit_tab_public_roles", :force => true do |t|
    t.integer  "edit_tab_id"
    t.integer  "class_id"
    t.integer  "uid"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_edit_tabs", :force => true do |t|
    t.integer  "class_created",        :default => 0
    t.string   "published"
    t.string   "state"
    t.integer  "level_no",             :default => 0
    t.integer  "parent_id",            :default => 0
    t.string   "name"
    t.integer  "sort_no",              :default => 0
    t.integer  "tab_keys",             :default => 0
    t.text     "display_auth"
    t.integer  "other_controller_use", :default => 2
    t.string   "other_controller_url"
    t.text     "link_url"
    t.text     "icon_path"
    t.string   "link_div_class"
    t.integer  "class_external",       :default => 0
    t.integer  "class_sso",            :default => 0
    t.string   "field_account"
    t.string   "field_pass"
    t.integer  "css_id",               :default => 0
    t.integer  "is_public"
    t.datetime "deleted_at"
    t.string   "deleted_user"
    t.string   "deleted_group"
    t.datetime "updated_at"
    t.string   "updated_user"
    t.string   "updated_group"
    t.datetime "created_at"
    t.string   "created_user"
    t.string   "created_group"
  end

  create_table "gw_holidays", :force => true do |t|
    t.integer  "creator_uid"
    t.string   "creator_ucode"
    t.text     "creator_uname"
    t.integer  "creator_gid"
    t.string   "creator_gcode"
    t.text     "creator_gname"
    t.integer  "title_category_id"
    t.string   "title"
    t.integer  "is_public"
    t.text     "memo"
    t.integer  "schedule_repeat_id"
    t.integer  "dirty_repeat_id"
    t.integer  "no_time_id"
    t.datetime "st_at"
    t.datetime "ed_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "gw_holidays", ["st_at", "ed_at"], :name => "st_at"

  create_table "gw_icon_groups", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_icons", :force => true do |t|
    t.integer  "icon_gid"
    t.integer  "idx"
    t.string   "title"
    t.string   "path"
    t.string   "content_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_ind_portal_pieces", :force => true do |t|
    t.integer  "uid"
    t.integer  "sort_no"
    t.text     "name",       :null => false
    t.text     "title"
    t.text     "piece"
    t.text     "genre"
    t.integer  "tid"
    t.integer  "limit"
    t.text     "position"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_infos", :force => true do |t|
    t.string   "cls"
    t.string   "title"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_memo_mobiles", :force => true do |t|
    t.string   "domain"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_memo_users", :force => true do |t|
    t.integer  "schedule_id"
    t.integer  "class_id"
    t.integer  "uid"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_memos", :force => true do |t|
    t.integer  "class_id"
    t.integer  "uid"
    t.string   "title"
    t.datetime "st_at"
    t.datetime "ed_at"
    t.integer  "is_finished"
    t.integer  "is_system"
    t.string   "fr_group"
    t.string   "fr_user"
    t.integer  "memo_category_id"
    t.string   "memo_category_text"
    t.text     "body"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_monitor_reminders", :force => true do |t|
    t.integer  "state"
    t.integer  "uid"
    t.string   "u_code"
    t.integer  "gid"
    t.string   "g_code"
    t.integer  "class_id"
    t.text     "title"
    t.datetime "st_at"
    t.datetime "ed_at"
    t.integer  "is_finished"
    t.integer  "is_system"
    t.text     "options"
    t.text     "body"
    t.datetime "deleted_at"
    t.datetime "updated_at"
    t.datetime "created_at"
  end

  add_index "gw_monitor_reminders", ["ed_at"], :name => "ed_at"
  add_index "gw_monitor_reminders", ["state"], :name => "state"
  add_index "gw_monitor_reminders", ["uid"], :name => "uid"

  create_table "gw_notes", :force => true do |t|
    t.integer  "uid"
    t.integer  "position"
    t.string   "title"
    t.text     "body"
    t.datetime "deadline"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_plus_updates", :force => true do |t|
    t.string   "doc_id"
    t.string   "post_id"
    t.string   "state"
    t.text     "project_users"
    t.text     "project_users_json"
    t.string   "project_id"
    t.string   "project_code"
    t.integer  "class_id"
    t.text     "title"
    t.datetime "doc_updated_at"
    t.text     "author"
    t.text     "project_url"
    t.text     "body"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_portal_adds", :force => true do |t|
    t.text     "state"
    t.text     "published"
    t.text     "file_path"
    t.text     "file_directory"
    t.text     "file_name"
    t.text     "original_file_name"
    t.text     "content_type"
    t.integer  "width"
    t.integer  "height"
    t.integer  "place"
    t.integer  "sort_no"
    t.text     "title"
    t.text     "body"
    t.text     "url"
    t.datetime "publish_start_at"
    t.datetime "publish_end_at"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "deleted_at"
    t.text     "deleted_user"
    t.text     "deleted_group"
  end

  create_table "gw_portal_user_settings", :force => true do |t|
    t.integer  "uid"
    t.integer  "idx"
    t.string   "arrange"
    t.string   "title"
    t.string   "gadget"
    t.string   "options"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_pref_assembly_members", :force => true do |t|
    t.integer  "gid"
    t.string   "g_code"
    t.string   "g_name"
    t.integer  "g_order"
    t.integer  "uid"
    t.string   "u_code"
    t.text     "u_lname"
    t.text     "u_name"
    t.integer  "u_order"
    t.text     "title"
    t.string   "state"
    t.datetime "deleted_at"
    t.string   "deleted_user"
    t.string   "deleted_group"
    t.datetime "updated_at"
    t.string   "updated_user"
    t.string   "updated_group"
    t.datetime "created_at"
    t.string   "created_user"
    t.string   "created_group"
  end

  create_table "gw_pref_directors", :force => true do |t|
    t.integer  "parent_gid"
    t.string   "parent_g_code"
    t.string   "parent_g_name"
    t.integer  "parent_g_order"
    t.integer  "gid"
    t.string   "g_code"
    t.string   "g_name"
    t.integer  "g_order"
    t.integer  "uid"
    t.string   "u_code"
    t.text     "u_lname"
    t.text     "u_name"
    t.integer  "u_order"
    t.text     "title"
    t.string   "state"
    t.datetime "deleted_at"
    t.string   "deleted_user"
    t.string   "deleted_group"
    t.datetime "updated_at"
    t.string   "updated_user"
    t.string   "updated_group"
    t.datetime "created_at"
    t.string   "created_user"
    t.string   "created_group"
    t.integer  "is_governor_view"
  end

  create_table "gw_pref_executives", :force => true do |t|
    t.integer  "parent_gid"
    t.string   "parent_g_code"
    t.string   "parent_g_name"
    t.integer  "parent_g_order"
    t.integer  "gid"
    t.string   "g_code"
    t.string   "g_name"
    t.integer  "g_order"
    t.integer  "uid"
    t.string   "u_code"
    t.text     "u_lname"
    t.text     "u_name"
    t.integer  "u_order"
    t.text     "title"
    t.string   "state"
    t.datetime "deleted_at"
    t.string   "deleted_user"
    t.string   "deleted_group"
    t.datetime "updated_at"
    t.string   "updated_user"
    t.string   "updated_group"
    t.datetime "created_at"
    t.string   "created_user"
    t.string   "created_group"
    t.integer  "is_other_view"
    t.integer  "is_governor_view"
  end

  create_table "gw_prop_admin_setting_roles", :force => true do |t|
    t.integer  "prop_setting_id"
    t.integer  "gid"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_prop_admin_settings", :force => true do |t|
    t.string   "name"
    t.integer  "type_id"
    t.integer  "span"
    t.integer  "span_limit"
    t.integer  "span_hour"
    t.integer  "span_min"
    t.integer  "time_limit"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_prop_group_settings", :force => true do |t|
    t.integer  "prop_group_id"
    t.integer  "prop_other_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_prop_groups", :force => true do |t|
    t.text     "state"
    t.string   "name"
    t.integer  "sort_no"
    t.integer  "parent_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
  end

  create_table "gw_prop_other_images", :force => true do |t|
    t.integer  "parent_id"
    t.integer  "idx"
    t.string   "note"
    t.string   "path"
    t.string   "orig_filename"
    t.string   "content_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_prop_other_limits", :force => true do |t|
    t.integer  "sort_no"
    t.string   "state"
    t.integer  "gid"
    t.integer  "limit"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_prop_other_roles", :force => true do |t|
    t.integer  "prop_id"
    t.integer  "gid"
    t.string   "auth"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "gw_prop_other_roles", ["prop_id"], :name => "prop_id"

  create_table "gw_prop_others", :force => true do |t|
    t.string   "sort_no"
    t.string   "name"
    t.integer  "type_id"
    t.text     "state"
    t.integer  "edit_state"
    t.integer  "delete_state",   :default => 0
    t.integer  "reserved_state", :default => 1
    t.text     "comment"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "extra_flag"
    t.text     "extra_data"
    t.integer  "gid"
    t.string   "gname"
    t.integer  "creator_uid"
    t.integer  "updater_uid"
  end

  create_table "gw_prop_types", :force => true do |t|
    t.string   "state"
    t.string   "name"
    t.integer  "sort_no"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
  end

  create_table "gw_reminders", :force => true do |t|
    t.integer  "user_id"
    t.string   "category"
    t.string   "sub_category"
    t.integer  "title_id"
    t.integer  "item_id"
    t.string   "title"
    t.datetime "datetime"
    t.string   "url"
    t.string   "action"
    t.datetime "seen_at"
    t.datetime "created_at",          :null => false
    t.datetime "updated_at",          :null => false
    t.datetime "expiration_datetime"
  end

  add_index "gw_reminders", ["user_id"], :name => "index_gw_reminders_on_user_id"

  create_table "gw_rss_caches", :force => true do |t|
    t.text     "uri"
    t.datetime "fetched"
    t.text     "title"
    t.datetime "published"
    t.text     "link"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_rss_reader_caches", :force => true do |t|
    t.integer  "rrid"
    t.text     "uri"
    t.text     "title"
    t.text     "link"
    t.datetime "fetched_at"
    t.datetime "published_at"
    t.datetime "updated_at"
    t.datetime "created_at"
  end

  create_table "gw_rss_readers", :force => true do |t|
    t.text     "state"
    t.integer  "sort_no"
    t.text     "title"
    t.text     "uri"
    t.integer  "max"
    t.integer  "interval"
    t.datetime "checked_at"
    t.datetime "fetched_at"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
    t.datetime "deleted_at"
    t.text     "deleted_user"
    t.text     "deleted_group"
  end

  create_table "gw_schedule_props", :force => true do |t|
    t.integer  "schedule_id"
    t.string   "prop_type"
    t.integer  "prop_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "extra_data"
    t.integer  "confirmed_uid"
    t.integer  "confirmed_gid"
    t.datetime "confirmed_at"
    t.integer  "rented_uid"
    t.integer  "rented_gid"
    t.datetime "rented_at"
    t.integer  "returned_uid"
    t.integer  "returned_gid"
    t.datetime "returned_at"
    t.integer  "cancelled_uid"
    t.integer  "cancelled_gid"
    t.datetime "cancelled_at"
    t.datetime "st_at"
    t.datetime "ed_at"
  end

  add_index "gw_schedule_props", ["prop_id"], :name => "prop_id"
  add_index "gw_schedule_props", ["schedule_id", "prop_type", "prop_id"], :name => "schedule_id"

  create_table "gw_schedule_public_roles", :force => true do |t|
    t.integer  "schedule_id"
    t.integer  "class_id"
    t.integer  "uid"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_schedule_repeats", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "st_date_at"
    t.datetime "ed_date_at"
    t.datetime "st_time_at"
    t.datetime "ed_time_at"
    t.integer  "class_id"
    t.string   "weekday_ids"
  end

  create_table "gw_schedule_users", :force => true do |t|
    t.integer  "schedule_id"
    t.integer  "class_id"
    t.integer  "uid"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "st_at"
    t.datetime "ed_at"
  end

  add_index "gw_schedule_users", ["schedule_id", "class_id", "uid"], :name => "schedule_id"
  add_index "gw_schedule_users", ["schedule_id"], :name => "schedule_id2"
  add_index "gw_schedule_users", ["uid"], :name => "uid"

  create_table "gw_schedules", :force => true do |t|
    t.integer  "creator_uid"
    t.string   "creator_ucode"
    t.text     "creator_uname"
    t.integer  "creator_gid"
    t.string   "creator_gcode"
    t.text     "creator_gname"
    t.integer  "updater_uid"
    t.string   "updater_ucode"
    t.text     "updater_uname"
    t.integer  "updater_gid"
    t.string   "updater_gcode"
    t.text     "updater_gname"
    t.integer  "owner_uid"
    t.string   "owner_ucode"
    t.text     "owner_uname"
    t.integer  "owner_gid"
    t.string   "owner_gcode"
    t.text     "owner_gname"
    t.integer  "title_category_id"
    t.string   "title"
    t.integer  "place_category_id"
    t.string   "place"
    t.integer  "to_go"
    t.integer  "is_public"
    t.integer  "is_pr"
    t.text     "memo"
    t.text     "admin_memo"
    t.integer  "repeat_id"
    t.integer  "schedule_repeat_id"
    t.integer  "dirty_repeat_id"
    t.integer  "no_time_id"
    t.integer  "schedule_parent_id"
    t.integer  "participant_nums_inner"
    t.integer  "participant_nums_outer"
    t.integer  "check_30_over"
    t.text     "inquire_to"
    t.datetime "st_at"
    t.datetime "ed_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "todo"
    t.integer  "allday"
    t.integer  "guide_state"
    t.integer  "guide_place_id"
    t.text     "guide_place"
    t.integer  "guide_ed_at"
    t.integer  "event_week"
    t.integer  "event_month"
    t.integer  "delete_state",           :default => 0
  end

  add_index "gw_schedules", ["ed_at"], :name => "ed_at"
  add_index "gw_schedules", ["schedule_repeat_id"], :name => "schedule_repeat_id"
  add_index "gw_schedules", ["st_at", "ed_at"], :name => "st_at"

  create_table "gw_section_admin_masters", :force => true do |t|
    t.text     "func_name"
    t.string   "state"
    t.integer  "edit_auth"
    t.integer  "management_parent_gid"
    t.integer  "management_gid"
    t.integer  "management_uid"
    t.integer  "range_class_id"
    t.integer  "division_parent_gid"
    t.integer  "division_gid"
    t.string   "management_ucode"
    t.integer  "fyear_id_sb04"
    t.string   "management_gcode"
    t.string   "division_gcode"
    t.integer  "management_uid_sb04"
    t.integer  "management_gid_sb04"
    t.integer  "division_gid_sb04"
    t.integer  "creator_uid"
    t.integer  "creator_gid"
    t.integer  "updator_uid"
    t.integer  "updator_gid"
    t.integer  "deleted_uid"
    t.integer  "deleted_gid"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
  end

  create_table "gw_todos", :force => true do |t|
    t.integer  "class_id"
    t.integer  "uid"
    t.string   "title"
    t.datetime "st_at"
    t.datetime "ed_at"
    t.integer  "is_finished"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "prior_id"
    t.integer  "category_id"
    t.text     "body"
  end

  create_table "gw_user_properties", :force => true do |t|
    t.integer  "class_id"
    t.string   "uid"
    t.string   "name"
    t.string   "type_name"
    t.text     "options"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "gw_workflow_controls", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.integer  "default_published"
    t.integer  "doc_body_size_capacity"
    t.integer  "doc_body_size_currently"
    t.integer  "upload_graphic_file_size_capacity"
    t.string   "upload_graphic_file_size_capacity_unit"
    t.integer  "upload_document_file_size_capacity"
    t.string   "upload_document_file_size_capacity_unit"
    t.integer  "upload_graphic_file_size_max"
    t.integer  "upload_document_file_size_max"
    t.decimal  "upload_graphic_file_size_currently",                    :precision => 17, :scale => 0
    t.decimal  "upload_document_file_size_currently",                   :precision => 17, :scale => 0
    t.integer  "commission_limit"
    t.string   "create_section"
    t.string   "create_section_flag"
    t.boolean  "addnew_forbidden"
    t.boolean  "edit_forbidden"
    t.boolean  "draft_forbidden"
    t.boolean  "delete_forbidden"
    t.boolean  "attachfile_index_use"
    t.integer  "importance"
    t.string   "form_name"
    t.text     "banner"
    t.string   "banner_position"
    t.text     "left_banner"
    t.text     "left_menu"
    t.string   "left_index_use",                          :limit => 1
    t.integer  "left_index_pattern"
    t.string   "left_index_bg_color"
    t.string   "default_mode"
    t.text     "other_system_link"
    t.boolean  "preview_mode"
    t.integer  "wallpaper_id"
    t.text     "wallpaper"
    t.text     "css"
    t.text     "font_color"
    t.integer  "icon_id"
    t.text     "icon"
    t.integer  "sort_no"
    t.text     "caption"
    t.boolean  "view_hide"
    t.boolean  "categoey_view"
    t.integer  "categoey_view_line"
    t.boolean  "monthly_view"
    t.integer  "monthly_view_line"
    t.boolean  "group_view"
    t.integer  "one_line_use"
    t.integer  "notification"
    t.boolean  "restrict_access"
    t.integer  "upload_system"
    t.string   "limit_date"
    t.string   "name"
    t.string   "title"
    t.integer  "category"
    t.string   "category1_name"
    t.string   "category2_name"
    t.string   "category3_name"
    t.integer  "recognize"
    t.text     "createdate"
    t.string   "createrdivision_id",                      :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                              :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",                       :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                               :limit => 20
    t.text     "editor"
    t.integer  "default_limit"
    t.string   "dbname"
    t.text     "admingrps"
    t.text     "admingrps_json"
    t.text     "adms"
    t.text     "adms_json"
    t.text     "dsp_admin_name"
    t.text     "editors"
    t.text     "editors_json"
    t.text     "readers"
    t.text     "readers_json"
    t.text     "sueditors"
    t.text     "sueditors_json"
    t.text     "sureaders"
    t.text     "sureaders_json"
    t.text     "help_display"
    t.text     "help_url"
    t.text     "help_admin_url"
    t.text     "notes_field01"
    t.text     "notes_field02"
    t.text     "notes_field03"
    t.text     "notes_field04"
    t.text     "notes_field05"
    t.text     "notes_field06"
    t.text     "notes_field07"
    t.text     "notes_field08"
    t.text     "notes_field09"
    t.text     "notes_field10"
    t.datetime "docslast_updated_at"
  end

  create_table "gw_workflow_custom_route_steps", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "custom_route_id"
    t.integer  "number"
  end

  create_table "gw_workflow_custom_route_users", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "step_id"
    t.integer  "user_id"
    t.text     "user_name"
    t.text     "user_gname"
  end

  create_table "gw_workflow_custom_routes", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "owner_uid"
    t.integer  "sort_no"
    t.text     "state"
    t.text     "name"
  end

  create_table "gw_workflow_docs", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "state"
    t.text     "title"
    t.text     "body",           :limit => 16777215
    t.datetime "expired_at"
    t.datetime "applied_at"
    t.string   "creater_id",     :limit => 20
    t.string   "creater_name",   :limit => 20
    t.string   "creater_gname",  :limit => 20
    t.integer  "attachmentfile"
  end

  create_table "gw_workflow_itemdeletes", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "admin_code"
    t.integer  "title_id"
    t.text     "board_title"
    t.string   "board_state"
    t.string   "board_view_hide"
    t.integer  "board_sort_no"
    t.integer  "public_doc_count"
    t.integer  "void_doc_count"
    t.string   "dbname"
    t.string   "limit_date"
    t.string   "board_limit_date"
  end

  create_table "gw_workflow_mail_settings", :force => true do |t|
    t.integer "unid"
    t.boolean "notifying"
  end

  create_table "gw_workflow_route_steps", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "doc_id"
    t.integer  "number"
  end

  create_table "gw_workflow_route_users", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "step_id"
    t.datetime "decided_at"
    t.string   "state"
    t.text     "comment"
    t.integer  "user_id"
    t.text     "user_name"
    t.text     "user_gname"
  end

  create_table "gw_year_fiscal_jps", :force => true do |t|
    t.datetime "start_at"
    t.datetime "end_at"
    t.text     "fyear"
    t.text     "fyear_f"
    t.text     "markjp"
    t.text     "markjp_f"
    t.text     "namejp"
    t.text     "namejp_f"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gw_year_mark_jps", :force => true do |t|
    t.text     "name"
    t.text     "mark"
    t.datetime "start_at"
    t.datetime "updated_at"
    t.text     "updated_user"
    t.text     "updated_group"
    t.datetime "created_at"
    t.text     "created_user"
    t.text     "created_group"
  end

  create_table "gwbbs_adms", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "gwbbs_controls", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.integer  "default_published"
    t.integer  "doc_body_size_capacity"
    t.integer  "doc_body_size_currently"
    t.integer  "upload_graphic_file_size_capacity"
    t.string   "upload_graphic_file_size_capacity_unit"
    t.integer  "upload_document_file_size_capacity"
    t.string   "upload_document_file_size_capacity_unit"
    t.integer  "upload_graphic_file_size_max"
    t.integer  "upload_document_file_size_max"
    t.decimal  "upload_graphic_file_size_currently",                    :precision => 17, :scale => 0
    t.decimal  "upload_document_file_size_currently",                   :precision => 17, :scale => 0
    t.string   "create_section"
    t.string   "create_section_flag"
    t.boolean  "addnew_forbidden"
    t.boolean  "edit_forbidden"
    t.boolean  "draft_forbidden"
    t.boolean  "delete_forbidden"
    t.boolean  "attachfile_index_use"
    t.integer  "importance"
    t.string   "form_name"
    t.text     "banner"
    t.string   "banner_position"
    t.text     "left_banner"
    t.text     "left_menu"
    t.string   "left_index_use",                          :limit => 1
    t.integer  "left_index_pattern"
    t.string   "left_index_bg_color"
    t.string   "default_mode"
    t.text     "other_system_link"
    t.boolean  "preview_mode"
    t.integer  "wallpaper_id"
    t.text     "wallpaper"
    t.text     "css"
    t.text     "font_color"
    t.integer  "icon_id"
    t.text     "icon"
    t.integer  "sort_no"
    t.text     "caption"
    t.boolean  "view_hide"
    t.boolean  "categoey_view"
    t.integer  "categoey_view_line"
    t.boolean  "monthly_view"
    t.integer  "monthly_view_line"
    t.boolean  "group_view"
    t.integer  "one_line_use"
    t.integer  "notification"
    t.boolean  "restrict_access"
    t.integer  "upload_system"
    t.string   "limit_date"
    t.string   "name"
    t.string   "title"
    t.integer  "category"
    t.string   "category1_name"
    t.string   "category2_name"
    t.string   "category3_name"
    t.integer  "recognize"
    t.text     "createdate"
    t.string   "createrdivision_id",                      :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                              :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",                       :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                               :limit => 20
    t.text     "editor"
    t.integer  "default_limit"
    t.string   "dbname"
    t.text     "admingrps"
    t.text     "admingrps_json"
    t.text     "adms"
    t.text     "adms_json"
    t.text     "dsp_admin_name"
    t.text     "editors"
    t.text     "editors_json"
    t.text     "readers"
    t.text     "readers_json"
    t.text     "sueditors"
    t.text     "sueditors_json"
    t.text     "sureaders"
    t.text     "sureaders_json"
    t.text     "help_display"
    t.text     "help_url"
    t.text     "help_admin_url"
    t.text     "notes_field01"
    t.text     "notes_field02"
    t.text     "notes_field03"
    t.text     "notes_field04"
    t.text     "notes_field05"
    t.text     "notes_field06"
    t.text     "notes_field07"
    t.text     "notes_field08"
    t.text     "notes_field09"
    t.text     "notes_field10"
    t.datetime "docslast_updated_at"
  end

  create_table "gwbbs_itemdeletes", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "admin_code"
    t.integer  "title_id"
    t.text     "board_title"
    t.string   "board_state"
    t.string   "board_view_hide"
    t.integer  "board_sort_no"
    t.integer  "public_doc_count"
    t.integer  "void_doc_count"
    t.string   "dbname"
    t.string   "limit_date"
    t.string   "board_limit_date"
  end

  create_table "gwbbs_roles", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.string   "role_code"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "gwbbs_themes", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.integer  "board_id"
    t.integer  "theme_id"
    t.text     "section_code"
    t.text     "section_name"
    t.text     "createdate"
    t.boolean  "creater_admin"
    t.string   "createrdivision_id", :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",         :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.boolean  "editor_admin"
    t.string   "editordivision_id",  :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",          :limit => 20
    t.text     "editor"
  end

  create_table "gwboard_bgcolors", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "state"
    t.string   "title"
    t.string   "color_code_hex"
    t.string   "color_code_class"
    t.string   "pair_font_color"
    t.text     "memo"
  end

  create_table "gwboard_images", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.integer  "share"
    t.integer  "range_of_use"
    t.text     "filename"
    t.string   "content_type"
    t.text     "memo"
    t.integer  "size"
    t.integer  "width"
    t.integer  "height"
    t.text     "section_code"
    t.text     "section_name"
    t.text     "createdate"
    t.boolean  "creater_admin"
    t.string   "createrdivision_id", :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",         :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.boolean  "editor_admin"
    t.string   "editordivision_id",  :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",          :limit => 20
    t.text     "editor"
  end

  create_table "gwboard_maps", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "state"
    t.string   "system_name"
    t.integer  "title_id"
    t.integer  "parent_id"
    t.string   "field_name"
    t.integer  "use_param"
    t.text     "address"
    t.string   "latlong"
    t.string   "latitude"
    t.string   "longitude"
    t.text     "memo"
    t.string   "url"
  end

  create_table "gwboard_renewal_groups", :force => true do |t|
    t.integer "present_group_id"
    t.string  "present_group_code"
    t.text    "present_group_name"
    t.integer "incoming_group_id"
    t.string  "incoming_group_code"
    t.text    "incoming_group_name"
  end

  create_table "gwboard_syntheses", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "latest_updated_at"
    t.string   "system_name"
    t.text     "state"
    t.integer  "title_id"
    t.integer  "parent_id"
    t.string   "board_name"
    t.text     "title"
    t.text     "url"
    t.text     "editordivision"
    t.text     "editor"
    t.datetime "able_date"
    t.datetime "expiry_date"
    t.integer  "acl_flag"
    t.string   "acl_section_code"
    t.string   "acl_user_code"
  end

  create_table "gwboard_synthesetups", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "gwbbs_check"
    t.boolean  "gwfaq_check"
    t.boolean  "gwqa_check"
    t.boolean  "doclib_check"
    t.boolean  "digitallib_check"
    t.string   "limit_date"
  end

  create_table "gwboard_themes", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.string   "record_use"
    t.integer  "sort_no"
    t.text     "if_name"
    t.integer  "if_icon_id"
    t.text     "if_icon"
    t.integer  "if_bg_setup"
    t.text     "if_font_color"
    t.integer  "if_wallpaper_id"
    t.text     "if_wallpaper"
    t.text     "if_css"
    t.text     "name"
    t.boolean  "preview_mode"
    t.integer  "bg_setup"
    t.integer  "icon_id"
    t.text     "icon"
    t.text     "css"
    t.text     "font_color"
    t.integer  "wallpaper_id"
    t.text     "wallpaper"
    t.text     "section_code"
    t.text     "section_name"
    t.text     "createdate"
    t.boolean  "creater_admin"
    t.string   "createrdivision_id", :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",         :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.boolean  "editor_admin"
    t.string   "editordivision_id",  :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",          :limit => 20
    t.text     "editor"
  end

  create_table "gwcircular_adms", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "gwcircular_controls", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.integer  "default_published"
    t.integer  "doc_body_size_capacity"
    t.integer  "doc_body_size_currently"
    t.integer  "upload_graphic_file_size_capacity"
    t.string   "upload_graphic_file_size_capacity_unit"
    t.integer  "upload_document_file_size_capacity"
    t.string   "upload_document_file_size_capacity_unit"
    t.integer  "upload_graphic_file_size_max"
    t.integer  "upload_document_file_size_max"
    t.decimal  "upload_graphic_file_size_currently",                    :precision => 17, :scale => 0
    t.decimal  "upload_document_file_size_currently",                   :precision => 17, :scale => 0
    t.integer  "commission_limit"
    t.string   "create_section"
    t.string   "create_section_flag"
    t.boolean  "addnew_forbidden"
    t.boolean  "edit_forbidden"
    t.boolean  "draft_forbidden"
    t.boolean  "delete_forbidden"
    t.boolean  "attachfile_index_use"
    t.integer  "importance"
    t.string   "form_name"
    t.text     "banner"
    t.string   "banner_position"
    t.text     "left_banner"
    t.text     "left_menu"
    t.string   "left_index_use",                          :limit => 1
    t.integer  "left_index_pattern"
    t.string   "left_index_bg_color"
    t.string   "default_mode"
    t.text     "other_system_link"
    t.boolean  "preview_mode"
    t.integer  "wallpaper_id"
    t.text     "wallpaper"
    t.text     "css"
    t.text     "font_color"
    t.integer  "icon_id"
    t.text     "icon"
    t.integer  "sort_no"
    t.text     "caption"
    t.boolean  "view_hide"
    t.boolean  "categoey_view"
    t.integer  "categoey_view_line"
    t.boolean  "monthly_view"
    t.integer  "monthly_view_line"
    t.boolean  "group_view"
    t.integer  "one_line_use"
    t.integer  "notification"
    t.boolean  "restrict_access"
    t.integer  "upload_system"
    t.string   "limit_date"
    t.string   "name"
    t.string   "title"
    t.integer  "category"
    t.string   "category1_name"
    t.string   "category2_name"
    t.string   "category3_name"
    t.integer  "recognize"
    t.text     "createdate"
    t.string   "createrdivision_id",                      :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                              :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",                       :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                               :limit => 20
    t.text     "editor"
    t.integer  "default_limit"
    t.string   "dbname"
    t.text     "admingrps"
    t.text     "admingrps_json"
    t.text     "adms"
    t.text     "adms_json"
    t.text     "dsp_admin_name"
    t.text     "editors"
    t.text     "editors_json"
    t.text     "readers"
    t.text     "readers_json"
    t.text     "sueditors"
    t.text     "sueditors_json"
    t.text     "sureaders"
    t.text     "sureaders_json"
    t.text     "help_display"
    t.text     "help_url"
    t.text     "help_admin_url"
    t.text     "notes_field01"
    t.text     "notes_field02"
    t.text     "notes_field03"
    t.text     "notes_field04"
    t.text     "notes_field05"
    t.text     "notes_field06"
    t.text     "notes_field07"
    t.text     "notes_field08"
    t.text     "notes_field09"
    t.text     "notes_field10"
    t.datetime "docslast_updated_at"
  end

  create_table "gwcircular_custom_groups", :force => true do |t|
    t.integer  "parent_id"
    t.integer  "class_id"
    t.integer  "owner_uid"
    t.integer  "owner_gid"
    t.integer  "updater_uid"
    t.integer  "updater_gid"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "level_no"
    t.text     "name"
    t.text     "name_en"
    t.integer  "sort_no"
    t.text     "sort_prefix"
    t.integer  "is_default"
    t.text     "reader_groups_json", :limit => 16777215
    t.text     "reader_groups",      :limit => 16777215
    t.text     "readers_json",       :limit => 16777215
    t.text     "readers",            :limit => 16777215
  end

  create_table "gwcircular_docs", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.integer  "doc_type"
    t.integer  "parent_id"
    t.integer  "target_user_id"
    t.string   "target_user_code",   :limit => 20
    t.text     "target_user_name"
    t.integer  "confirmation"
    t.string   "section_code"
    t.text     "section_name"
    t.integer  "importance"
    t.integer  "title_id"
    t.text     "name"
    t.text     "title"
    t.text     "head",               :limit => 16777215
    t.text     "body",               :limit => 16777215
    t.text     "note",               :limit => 16777215
    t.integer  "category_use"
    t.integer  "category1_id"
    t.integer  "category2_id"
    t.integer  "category3_id"
    t.integer  "category4_id"
    t.text     "keywords"
    t.integer  "commission_count"
    t.integer  "unread_count"
    t.integer  "already_count"
    t.integer  "draft_count"
    t.text     "createdate"
    t.boolean  "creater_admin"
    t.string   "createrdivision_id", :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",         :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.boolean  "editor_admin"
    t.string   "editordivision_id",  :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",          :limit => 20
    t.text     "editor"
    t.datetime "able_date"
    t.datetime "expiry_date"
    t.integer  "attachmentfile"
    t.text     "reader_groups_json", :limit => 16777215
    t.text     "reader_groups",      :limit => 16777215
    t.text     "readers_json",       :limit => 16777215
    t.text     "readers",            :limit => 16777215
    t.integer  "spec_config"
  end

  add_index "gwcircular_docs", ["parent_id"], :name => "parent_id"
  add_index "gwcircular_docs", ["title_id", "doc_type", "target_user_code", "state", "able_date", "createrdivision_id"], :name => "index_for_createrdivision_search", :length => {"title_id"=>nil, "doc_type"=>nil, "target_user_code"=>nil, "state"=>20, "able_date"=>nil, "createrdivision_id"=>nil}
  add_index "gwcircular_docs", ["title_id", "doc_type", "target_user_code", "state", "created_at", "able_date"], :name => "index_for_monthly_search", :length => {"title_id"=>nil, "doc_type"=>nil, "target_user_code"=>nil, "state"=>20, "created_at"=>nil, "able_date"=>nil}

  create_table "gwcircular_files", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.integer  "parent_id"
    t.integer  "title_id"
    t.string   "content_type"
    t.text     "filename"
    t.text     "memo"
    t.integer  "size"
    t.integer  "width"
    t.integer  "height"
    t.integer  "db_file_id"
  end

  create_table "gwcircular_itemdeletes", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "admin_code"
    t.integer  "title_id"
    t.text     "board_title"
    t.string   "board_state"
    t.string   "board_view_hide"
    t.integer  "board_sort_no"
    t.integer  "public_doc_count"
    t.integer  "void_doc_count"
    t.string   "dbname"
    t.string   "limit_date"
    t.string   "board_limit_date"
  end

  create_table "gwcircular_roles", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.string   "role_code"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "gwfaq_adms", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "gwfaq_controls", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.integer  "default_published"
    t.integer  "upload_graphic_file_size_capacity"
    t.string   "upload_graphic_file_size_capacity_unit"
    t.integer  "upload_document_file_size_capacity"
    t.string   "upload_document_file_size_capacity_unit"
    t.integer  "upload_graphic_file_size_max"
    t.integer  "upload_document_file_size_max"
    t.decimal  "upload_graphic_file_size_currently",                    :precision => 17, :scale => 0
    t.decimal  "upload_document_file_size_currently",                   :precision => 17, :scale => 0
    t.string   "create_section"
    t.integer  "addnew_forbidden"
    t.integer  "draft_forbidden"
    t.integer  "delete_forbidden"
    t.integer  "importance"
    t.string   "form_name"
    t.text     "banner"
    t.string   "banner_position"
    t.text     "left_banner"
    t.text     "left_menu"
    t.string   "left_index_use",                          :limit => 1
    t.integer  "left_index_pattern"
    t.string   "left_index_bg_color"
    t.text     "other_system_link"
    t.text     "wallpaper"
    t.text     "css"
    t.integer  "sort_no"
    t.text     "caption"
    t.boolean  "view_hide"
    t.boolean  "categoey_view"
    t.integer  "categoey_view_line"
    t.boolean  "monthly_view"
    t.integer  "monthly_view_line"
    t.boolean  "group_view"
    t.integer  "notification"
    t.integer  "upload_system"
    t.string   "limit_date"
    t.string   "name"
    t.string   "title"
    t.integer  "category"
    t.string   "category1_name"
    t.string   "category2_name"
    t.string   "category3_name"
    t.integer  "recognize"
    t.text     "createdate"
    t.string   "createrdivision_id",                      :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                              :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",                       :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                               :limit => 20
    t.text     "editor"
    t.integer  "default_limit"
    t.string   "dbname"
    t.text     "admingrps"
    t.text     "admingrps_json"
    t.text     "adms"
    t.text     "adms_json"
    t.text     "dsp_admin_name"
    t.text     "editors"
    t.text     "editors_json"
    t.text     "readers"
    t.text     "readers_json"
    t.text     "sueditors"
    t.text     "sueditors_json"
    t.text     "sureaders"
    t.text     "sureaders_json"
    t.text     "help_display"
    t.text     "help_url"
    t.text     "help_admin_url"
    t.datetime "docslast_updated_at"
  end

  create_table "gwfaq_recognizers", :force => true do |t|
    t.integer  "unid"
    t.datetime "updated_at"
    t.datetime "created_at"
    t.integer  "title_id"
    t.integer  "parent_id"
    t.integer  "user_id"
    t.string   "code"
    t.text     "name"
    t.datetime "recognized_at"
  end

  create_table "gwfaq_roles", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.string   "role_code"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "gwmonitor_base_files", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.integer  "parent_id"
    t.integer  "title_id"
    t.string   "content_type"
    t.text     "filename"
    t.text     "memo"
    t.integer  "size"
    t.integer  "width"
    t.integer  "height"
    t.integer  "db_file_id"
  end

  create_table "gwmonitor_controls", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "latest_updated_at"
    t.string   "section_code"
    t.string   "section_name"
    t.integer  "section_sort"
    t.string   "name"
    t.integer  "form_id"
    t.string   "form_name"
    t.string   "form_caption"
    t.integer  "upload_system"
    t.integer  "admin_setting"
    t.integer  "spec_config"
    t.string   "title"
    t.text     "caption"
    t.datetime "able_date"
    t.datetime "expiry_date"
    t.integer  "reminder_start_section"
    t.integer  "reminder_start_personal"
    t.integer  "public_count"
    t.integer  "draft_count"
    t.text     "createdate"
    t.string   "createrdivision_id",                      :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                              :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",                       :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                               :limit => 20
    t.text     "editor"
    t.integer  "default_limit"
    t.text     "dsp_admin_name"
    t.string   "send_change"
    t.text     "custom_groups"
    t.text     "custom_groups_json"
    t.text     "reader_groups"
    t.text     "reader_groups_json"
    t.text     "custom_readers"
    t.text     "custom_readers_json"
    t.text     "readers"
    t.text     "readers_json"
    t.integer  "upload_graphic_file_size_capacity"
    t.string   "upload_graphic_file_size_capacity_unit"
    t.integer  "upload_document_file_size_capacity"
    t.string   "upload_document_file_size_capacity_unit"
    t.integer  "upload_graphic_file_size_max"
    t.integer  "upload_document_file_size_max"
    t.decimal  "upload_graphic_file_size_currently",                    :precision => 17, :scale => 0
    t.decimal  "upload_document_file_size_currently",                   :precision => 17, :scale => 0
  end

  create_table "gwmonitor_custom_groups", :force => true do |t|
    t.integer  "parent_id"
    t.integer  "class_id"
    t.integer  "owner_uid"
    t.integer  "owner_gid"
    t.integer  "updater_uid"
    t.integer  "updater_gid"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "level_no"
    t.text     "name"
    t.text     "name_en"
    t.integer  "sort_no"
    t.text     "sort_prefix"
    t.integer  "is_default"
    t.text     "reader_groups_json", :limit => 16777215
    t.text     "reader_groups",      :limit => 16777215
    t.text     "readers_json",       :limit => 16777215
    t.text     "readers",            :limit => 16777215
  end

  create_table "gwmonitor_custom_user_groups", :force => true do |t|
    t.integer  "parent_id"
    t.integer  "class_id"
    t.integer  "owner_uid"
    t.integer  "owner_gid"
    t.integer  "updater_uid"
    t.integer  "updater_gid"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "level_no"
    t.text     "name"
    t.text     "name_en"
    t.integer  "sort_no"
    t.text     "sort_prefix"
    t.integer  "is_default"
    t.text     "reader_groups_json", :limit => 16777215
    t.text     "reader_groups",      :limit => 16777215
    t.text     "readers_json",       :limit => 16777215
    t.text     "readers",            :limit => 16777215
  end

  create_table "gwmonitor_docs", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "latest_updated_at"
    t.integer  "send_division"
    t.string   "user_code",                  :limit => 20
    t.string   "user_name"
    t.string   "l2_section_code"
    t.string   "section_code"
    t.text     "section_name"
    t.integer  "section_sort"
    t.string   "email"
    t.boolean  "email_send"
    t.integer  "title_id"
    t.text     "name"
    t.text     "title"
    t.text     "head",                       :limit => 16777215
    t.text     "body",                       :limit => 16777215
    t.text     "note",                       :limit => 16777215
    t.text     "keywords"
    t.text     "createdate"
    t.boolean  "creater_admin"
    t.string   "createrdivision_id",         :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                 :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.boolean  "editor_admin"
    t.string   "editordivision_id",          :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                  :limit => 20
    t.text     "editor"
    t.datetime "able_date"
    t.datetime "expiry_date"
    t.datetime "remind_start_date"
    t.datetime "remind_start_date_personal"
    t.string   "receipt_user_code"
    t.integer  "attachmentfile"
  end

  create_table "gwmonitor_files", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.integer  "parent_id"
    t.integer  "title_id"
    t.string   "content_type"
    t.text     "filename"
    t.text     "memo"
    t.integer  "size"
    t.integer  "width"
    t.integer  "height"
    t.integer  "db_file_id"
  end

  create_table "gwmonitor_forms", :force => true do |t|
    t.integer  "unid"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "sort_no"
    t.integer  "level_no"
    t.string   "form_name"
    t.text     "form_caption"
  end

  create_table "gwmonitor_itemdeletes", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "admin_code"
    t.integer  "title_id"
    t.text     "board_title"
    t.string   "board_state"
    t.string   "board_view_hide"
    t.integer  "board_sort_no"
    t.integer  "public_doc_count"
    t.integer  "void_doc_count"
    t.string   "dbname"
    t.string   "limit_date"
    t.string   "board_limit_date"
  end

  create_table "gwqa_adms", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "gwqa_controls", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.integer  "default_published"
    t.integer  "upload_graphic_file_size_capacity"
    t.string   "upload_graphic_file_size_capacity_unit"
    t.integer  "upload_document_file_size_capacity"
    t.string   "upload_document_file_size_capacity_unit"
    t.integer  "upload_graphic_file_size_max"
    t.integer  "upload_document_file_size_max"
    t.decimal  "upload_graphic_file_size_currently",                    :precision => 17, :scale => 0
    t.decimal  "upload_document_file_size_currently",                   :precision => 17, :scale => 0
    t.string   "create_section"
    t.integer  "addnew_forbidden"
    t.integer  "draft_forbidden"
    t.integer  "delete_forbidden"
    t.integer  "importance"
    t.string   "form_name"
    t.text     "banner"
    t.string   "banner_position"
    t.text     "left_banner"
    t.text     "left_menu"
    t.string   "left_index_use",                          :limit => 1
    t.integer  "left_index_pattern"
    t.string   "left_index_bg_color"
    t.text     "other_system_link"
    t.text     "wallpaper"
    t.text     "css"
    t.integer  "sort_no"
    t.text     "caption"
    t.boolean  "view_hide"
    t.boolean  "categoey_view"
    t.integer  "categoey_view_line"
    t.boolean  "monthly_view"
    t.integer  "monthly_view_line"
    t.boolean  "group_view"
    t.integer  "notification"
    t.integer  "upload_system"
    t.string   "limit_date"
    t.string   "name"
    t.string   "title"
    t.integer  "category"
    t.string   "category1_name"
    t.string   "category2_name"
    t.string   "category3_name"
    t.integer  "recognize"
    t.text     "createdate"
    t.string   "createrdivision_id",                      :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",                              :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",                       :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",                               :limit => 20
    t.text     "editor"
    t.integer  "default_limit"
    t.string   "dbname"
    t.text     "admingrps"
    t.text     "admingrps_json"
    t.text     "adms"
    t.text     "adms_json"
    t.text     "dsp_admin_name"
    t.text     "editors"
    t.text     "editors_json"
    t.text     "readers"
    t.text     "readers_json"
    t.text     "sueditors"
    t.text     "sueditors_json"
    t.text     "sureaders"
    t.text     "sureaders_json"
    t.text     "help_display"
    t.text     "help_url"
    t.text     "help_admin_url"
    t.datetime "docslast_updated_at"
  end

  create_table "gwqa_recognizers", :force => true do |t|
    t.integer  "unid"
    t.datetime "updated_at"
    t.datetime "created_at"
    t.integer  "title_id"
    t.integer  "parent_id"
    t.integer  "user_id"
    t.string   "code"
    t.text     "name"
    t.datetime "recognized_at"
  end

  create_table "gwqa_roles", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.datetime "created_at"
    t.integer  "title_id"
    t.string   "role_code"
    t.integer  "user_id"
    t.string   "user_code"
    t.text     "user_name"
    t.integer  "group_id"
    t.string   "group_code"
    t.text     "group_name"
  end

  create_table "gwworkflow_files", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "recognized_at"
    t.datetime "published_at"
    t.datetime "latest_updated_at"
    t.integer  "parent_id"
    t.integer  "title_id"
    t.string   "content_type"
    t.text     "filename"
    t.text     "memo"
    t.integer  "size"
    t.integer  "width"
    t.integer  "height"
    t.integer  "db_file_id"
  end

  create_table "questionnaire_bases", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "section_code"
    t.string   "section_name"
    t.integer  "section_sort"
    t.boolean  "enquete_division"
    t.integer  "admin_setting"
    t.string   "manage_title"
    t.string   "title"
    t.text     "form_body"
    t.datetime "able_date"
    t.datetime "expiry_date"
    t.integer  "spec_config"
    t.string   "send_change"
    t.text     "remarks"
    t.text     "remarks_setting"
    t.text     "createdate"
    t.string   "createrdivision_id",  :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",          :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",   :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",           :limit => 20
    t.text     "editor"
    t.text     "custom_groups"
    t.text     "custom_groups_json"
    t.text     "reader_groups"
    t.text     "reader_groups_json"
    t.text     "custom_readers"
    t.text     "custom_readers_json"
    t.text     "readers"
    t.text     "readers_json"
    t.integer  "default_limit"
    t.integer  "answer_count"
    t.boolean  "include_index"
    t.boolean  "result_open_state"
    t.string   "keycode"
  end

  create_table "questionnaire_field_options", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "published_at"
    t.integer  "field_id"
    t.integer  "sort_no"
    t.string   "value"
    t.text     "title"
  end

  create_table "questionnaire_form_fields", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "parent_id"
    t.integer  "sort_no"
    t.string   "question_type"
    t.string   "title"
    t.string   "field_cols"
    t.string   "field_rows"
    t.integer  "post_permit_base"
    t.integer  "post_permit"
    t.string   "post_permit_value"
    t.text     "option_body"
    t.string   "field_name"
    t.integer  "view_type"
    t.integer  "required_entry"
    t.boolean  "auto_number_state"
    t.integer  "auto_number"
    t.integer  "group_code"
    t.string   "group_field"
    t.text     "group_body"
    t.integer  "group_repeat"
  end

  create_table "questionnaire_itemdeletes", :force => true do |t|
    t.integer  "content_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "admin_code"
    t.string   "limit_date"
  end

  create_table "questionnaire_previews", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "parent_id"
    t.text     "field_001"
    t.text     "field_002"
    t.text     "field_003"
    t.text     "field_004"
    t.text     "field_005"
    t.text     "field_006"
    t.text     "field_007"
    t.text     "field_008"
    t.text     "field_009"
    t.text     "field_010"
    t.text     "field_011"
    t.text     "field_012"
    t.text     "field_013"
    t.text     "field_014"
    t.text     "field_015"
    t.text     "field_016"
    t.text     "field_017"
    t.text     "field_018"
    t.text     "field_019"
    t.text     "field_020"
    t.text     "field_021"
    t.text     "field_022"
    t.text     "field_023"
    t.text     "field_024"
    t.text     "field_025"
    t.text     "field_026"
    t.text     "field_027"
    t.text     "field_028"
    t.text     "field_029"
    t.text     "field_030"
    t.text     "field_031"
    t.text     "field_032"
    t.text     "field_033"
    t.text     "field_034"
    t.text     "field_035"
    t.text     "field_036"
    t.text     "field_037"
    t.text     "field_038"
    t.text     "field_039"
    t.text     "field_040"
    t.text     "field_041"
    t.text     "field_042"
    t.text     "field_043"
    t.text     "field_044"
    t.text     "field_045"
    t.text     "field_046"
    t.text     "field_047"
    t.text     "field_048"
    t.text     "field_049"
    t.text     "field_050"
    t.text     "field_051"
    t.text     "field_052"
    t.text     "field_053"
    t.text     "field_054"
    t.text     "field_055"
    t.text     "field_056"
    t.text     "field_057"
    t.text     "field_058"
    t.text     "field_059"
    t.text     "field_060"
    t.text     "field_061"
    t.text     "field_062"
    t.text     "field_063"
    t.text     "field_064"
    t.text     "createdate"
    t.string   "createrdivision_id", :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",         :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",  :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",          :limit => 20
    t.text     "editor"
  end

  create_table "questionnaire_results", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "title_id"
    t.integer  "field_id"
    t.string   "question_type"
    t.text     "question_label"
    t.integer  "option_id"
    t.text     "option_label"
    t.integer  "sort_no"
    t.integer  "answer_count"
    t.decimal  "answer_ratio",   :precision => 10, :scale => 5
  end

  create_table "questionnaire_template_bases", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "section_code"
    t.string   "section_name"
    t.integer  "section_sort"
    t.boolean  "enquete_division"
    t.integer  "admin_setting"
    t.string   "manage_title"
    t.string   "title"
    t.text     "form_body"
    t.datetime "able_date"
    t.datetime "expiry_date"
    t.integer  "spec_config"
    t.string   "send_change"
    t.text     "createdate"
    t.string   "createrdivision_id",  :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",          :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",   :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",           :limit => 20
    t.text     "editor"
    t.text     "custom_groups"
    t.text     "custom_groups_json"
    t.text     "reader_groups"
    t.text     "reader_groups_json"
    t.text     "custom_readers"
    t.text     "custom_readers_json"
    t.text     "readers"
    t.text     "readers_json"
    t.integer  "default_limit"
  end

  create_table "questionnaire_template_field_options", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "published_at"
    t.integer  "field_id"
    t.integer  "sort_no"
    t.string   "value"
    t.text     "title"
  end

  create_table "questionnaire_template_form_fields", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "parent_id"
    t.integer  "sort_no"
    t.string   "question_type"
    t.string   "title"
    t.string   "field_cols"
    t.string   "field_rows"
    t.integer  "post_permit_base"
    t.integer  "post_permit"
    t.string   "post_permit_value"
    t.text     "option_body"
    t.string   "field_name"
    t.integer  "view_type"
    t.integer  "required_entry"
    t.boolean  "auto_number_state"
    t.integer  "auto_number"
    t.integer  "group_code"
    t.string   "group_field"
    t.text     "group_body"
    t.integer  "group_repeat"
  end

  create_table "questionnaire_template_previews", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "parent_id"
    t.text     "field_001"
    t.text     "field_002"
    t.text     "field_003"
    t.text     "field_004"
    t.text     "field_005"
    t.text     "field_006"
    t.text     "field_007"
    t.text     "field_008"
    t.text     "field_009"
    t.text     "field_010"
    t.text     "field_011"
    t.text     "field_012"
    t.text     "field_013"
    t.text     "field_014"
    t.text     "field_015"
    t.text     "field_016"
    t.text     "field_017"
    t.text     "field_018"
    t.text     "field_019"
    t.text     "field_020"
    t.text     "field_021"
    t.text     "field_022"
    t.text     "field_023"
    t.text     "field_024"
    t.text     "field_025"
    t.text     "field_026"
    t.text     "field_027"
    t.text     "field_028"
    t.text     "field_029"
    t.text     "field_030"
    t.text     "field_031"
    t.text     "field_032"
    t.text     "field_033"
    t.text     "field_034"
    t.text     "field_035"
    t.text     "field_036"
    t.text     "field_037"
    t.text     "field_038"
    t.text     "field_039"
    t.text     "field_040"
    t.text     "field_041"
    t.text     "field_042"
    t.text     "field_043"
    t.text     "field_044"
    t.text     "field_045"
    t.text     "field_046"
    t.text     "field_047"
    t.text     "field_048"
    t.text     "field_049"
    t.text     "field_050"
    t.text     "field_051"
    t.text     "field_052"
    t.text     "field_053"
    t.text     "field_054"
    t.text     "field_055"
    t.text     "field_056"
    t.text     "field_057"
    t.text     "field_058"
    t.text     "field_059"
    t.text     "field_060"
    t.text     "field_061"
    t.text     "field_062"
    t.text     "field_063"
    t.text     "field_064"
    t.text     "createdate"
    t.string   "createrdivision_id", :limit => 20
    t.text     "createrdivision"
    t.string   "creater_id",         :limit => 20
    t.text     "creater"
    t.text     "editdate"
    t.string   "editordivision_id",  :limit => 20
    t.text     "editordivision"
    t.string   "editor_id",          :limit => 20
    t.text     "editor"
  end

  create_table "questionnaire_temporaries", :force => true do |t|
    t.integer  "unid"
    t.integer  "content_id"
    t.text     "state"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "title_id"
    t.integer  "field_id"
    t.string   "question_type"
    t.text     "answer_text"
    t.integer  "answer_option"
  end

  add_index "questionnaire_temporaries", ["title_id"], :name => "title_id"

end
